export const companyTeams = [
  {
    id: 1,
    name: 'Frontend Development',
    type: 'frontend',
    description: 'Building beautiful and responsive user interfaces.',
    tags: ['React', 'Vue', 'Angular', 'UI/UX'],
    membersCount: 15,
  },
  {
    id: 2,
    name: 'Backend Engineering',
    type: 'backend',
    description: 'Crafting robust and scalable server-side applications.',
    tags: ['Node.js', 'Python', 'Java', 'APIs', 'Databases'],
    membersCount: 12,
  },
  {
    id: 3,
    name: 'Cloud Infrastructure',
    type: 'cloud',
    description: 'Managing and optimizing our cloud environments (AWS, Azure, GCP).',
    tags: ['AWS', 'Azure', 'GCP', 'DevOps', 'Kubernetes'],
    membersCount: 8,
  },
  {
    id: 4,
    name: 'Artificial Intelligence',
    type: 'ai',
    description: 'Developing intelligent systems and machine learning models.',
    tags: ['Machine Learning', 'Deep Learning', 'NLP', 'Computer Vision'],
    membersCount: 10,
  },
  {
    id: 5,
    name: 'Data Analytics',
    type: 'data analytics',
    description: 'Extracting insights from data to drive business decisions.',
    tags: ['SQL', 'Tableau', 'Power BI', 'Data Modeling'],
    membersCount: 7,
  },
  {
    id: 6,
    name: 'Quality Assurance',
    type: 'qa',
    description: 'Ensuring the quality and reliability of our software products.',
    tags: ['Testing', 'Automation', 'Manual Testing', 'QA'],
    membersCount: 6,
  },
  {
    id: 7,
    name: 'Product Management',
    type: 'management',
    description: 'Defining product vision, strategy, and roadmap.',
    tags: ['Product Strategy', 'Roadmapping', 'Agile', 'Market Research'],
    membersCount: 5,
  },
];